FROM python:3.12.2-bookworm

WORKDIR /usr/src/app

#https://pypi.org/project/pixivpy3/#history
RUN pip3 install pixivpy3==3.7.5
#https://pypi.org/project/elasticsearch/8.12.1/
RUN pip3 install elasticsearch==8.12.1


CMD ["python3"]